# Heart Disease Exploration

Authors: Sophie Groenwold, Priyanka Banerjee

In [20]:
import numpy as np
import altair as alt
import pandas as pd

In [26]:
kaggle_df = pd.read_csv('heart.csv')
# kaggle_df.head(10)
kaggle_df = kaggle_df.sort_values(by=['age'])
kaggle_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72    29    1   1       130   204    0        0      202      0      0.0   
58    34    1   3       118   182    0        0      174      0      0.0   
125   34    0   1       118   210    0        1      192      0      0.7   
239   35    1   0       126   282    0        0      156      1      0.0   
65    35    0   0       138   183    0        1      182      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
60    71    0   2       110   265    1        0      130      0      0.0   
151   71    0   0       112   149    0        1      125      0      1.6   
129   74    0   1       120   269    0        0      121      1      0.2   
144   76    0   2       140   197    0        2      116      0      1.1   
238   77    1   0       125   304    0        0      162      1      0.0   

     slope  ca  thal  target  
72       2   0     2       1  
58       2   0     2       1  
125      2   0     2       1  
239      2   0     3       0  
65       2   0     2       1  
..     ...  ..   ...     ...  
60       2   1     2       1  
151      1   0     2       1  
129      2   1     2       1  
144      1   0     2       1  
238      2   3     2       0  

[303 rows x 14 columns]

In [27]:
cleveland_df = pd.read_csv('processed_cleveland.csv')
# cleveland_df.head(10)
cleveland_df = cleveland_df.sort_values(by=['a'])
cleveland_df

a    b    c      d      e    f    g      h    i    j    k    l    m  n
132  29.0  1.0  2.0  130.0  204.0  0.0  2.0  202.0  0.0  0.0  1.0  0.0  3.0  0
101  34.0  1.0  1.0  118.0  182.0  0.0  2.0  174.0  0.0  0.0  1.0  0.0  3.0  0
225  34.0  0.0  2.0  118.0  210.0  0.0  0.0  192.0  0.0  0.7  1.0  0.0  3.0  0
283  35.0  1.0  2.0  122.0  192.0  0.0  0.0  174.0  0.0  0.0  1.0  0.0  3.0  0
117  35.0  0.0  4.0  138.0  183.0  0.0  0.0  182.0  0.0  1.4  1.0  0.0  3.0  0
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ... ..
42   71.0  0.0  2.0  160.0  302.0  0.0  0.0  162.0  0.0  0.4  1.0  2.0  3.0  0
103  71.0  0.0  3.0  110.0  265.0  1.0  2.0  130.0  0.0  0.0  1.0  1.0  3.0  0
233  74.0  0.0  2.0  120.0  269.0  0.0  2.0  121.0  1.0  0.2  1.0  1.0  3.0  0
257  76.0  0.0  3.0  140.0  197.0  0.0  1.0  116.0  0.0  1.1  2.0  0.0  3.0  0
161  77.0  1.0  4.0  125.0  304.0  0.0  2.0  162.0  1.0  0.0  1.0  3.0  3.0  4

[303 rows x 14 columns]

In [23]:
# to view all the range of values for each feature
for col in kaggle_df:
    print(kaggle_df[col].unique())

[63 37 41 56 57 44 52 54 48 49 64 58 50 66 43 69 59 42 61 40 71 51 65 53
 46 45 39 47 62 34 35 29 55 60 67 68 74 76 70 38 77]
[1 0]
[3 2 1 0]
[145 130 120 140 172 150 110 135 160 105 125 142 155 104 138 128 108 134
 122 115 118 100 124  94 112 102 152 101 132 148 178 129 180 136 126 106
 156 170 146 117 200 165 174 192 144 123 154 114 164]
[233 250 204 236 354 192 294 263 199 168 239 275 266 211 283 219 340 226
 247 234 243 302 212 175 417 197 198 177 273 213 304 232 269 360 308 245
 208 264 321 325 235 257 216 256 231 141 252 201 222 260 182 303 265 309
 186 203 183 220 209 258 227 261 221 205 240 318 298 564 277 214 248 255
 207 223 288 160 394 315 246 244 270 195 196 254 126 313 262 215 193 271
 268 267 210 295 306 178 242 180 228 149 278 253 342 157 286 229 284 224
 206 167 230 335 276 353 225 330 290 172 305 188 282 185 326 274 164 307
 249 341 407 217 174 281 289 322 299 300 293 184 409 259 200 327 237 218
 319 166 311 169 187 176 241 131]
[1 0]
[0 1 2]
[150 187 172 178 163 148 1

In [24]:
for col in cleveland_df:
    print(cleveland_df[col].unique())

[63. 67. 37. 41. 56. 62. 57. 53. 44. 52. 48. 54. 49. 64. 58. 60. 50. 66.
 43. 40. 69. 59. 42. 55. 61. 65. 71. 51. 46. 45. 39. 68. 47. 34. 35. 29.
 70. 77. 38. 74. 76.]
[1. 0.]
[1. 4. 3. 2.]
[145. 160. 120. 130. 140. 172. 150. 110. 132. 117. 135. 112. 105. 124.
 125. 142. 128. 170. 155. 104. 180. 138. 108. 134. 122. 115. 118. 100.
 200.  94. 165. 102. 152. 101. 126. 174. 148. 178. 158. 192. 129. 144.
 123. 136. 146. 106. 156. 154. 114. 164.]
[233. 286. 229. 250. 204. 236. 268. 354. 254. 203. 192. 294. 256. 263.
 199. 168. 239. 275. 266. 211. 283. 284. 224. 206. 219. 340. 226. 247.
 167. 230. 335. 234. 177. 276. 353. 243. 225. 302. 212. 330. 175. 417.
 197. 198. 290. 253. 172. 273. 213. 305. 216. 304. 188. 282. 185. 232.
 326. 231. 269. 267. 248. 360. 258. 308. 245. 270. 208. 264. 321. 274.
 325. 235. 257. 164. 141. 252. 255. 201. 222. 260. 182. 303. 265. 309.
 307. 249. 186. 341. 183. 407. 217. 288. 220. 209. 227. 261. 174. 281.
 221. 205. 240. 289. 318. 298. 564. 246. 322. 299. 300. 29

In [ ]:
for col1 in cleveland_df:
    for col2 in kaggle_df:
        